[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.bcmath",
  "nodejs_18"
]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev"
]

[start]
# El flag --force es vital en producción para que no pida confirmación
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"