[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo_mysql",
    "composer",
    "nodejs_20"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction --no-scripts",
    "npm install",
    "npm run build",
    # Movemos el manifest a donde Laravel lo espera
    "cp public/build/.vite/manifest.json public/build/manifest.json || true",
    "php artisan storage:link"
]

[start]
cmd = "php artisan config:cache && php artisan migrate --force && /start-container.sh"