[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.curl",
  "php82Packages.composer",
  "nodejs_18"
]

[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-interaction --no-scripts"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
