[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo_mysql",
    "php82Extensions.gd",
    "composer",
    "nodejs_20"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction --no-scripts",
    "npm install",
    "npm run build",
    # Buscamos el manifest donde sea que esté y lo movemos a la raíz de build
    "find public/build -name 'manifest.json' -exec cp {} public/build/manifest.json \\;",
    "php artisan storage:link"
]

[start]
# Añadimos config:clear para que Laravel olvide cualquier ruta vieja de tu PC
cmd = "php artisan config:clear && php artisan migrate --force && /start-container.sh"