services:
  - type: web
    name: velstore
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-interaction --no-scripts
      npm install
      npm run build
      php artisan storage:link
    startCommand: chmod +x render-start.sh && ./render-start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
    healthCheckPath: /

